services:
  - type: web
    name: riomedica-backend
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 5000
